mod init;
mod spawn;
mod build_base;
mod train_warrior;
mod take_warrior;
mod claim_airdrop;
mod send_troop;
mod retreat_troop;
mod enter_land;
mod go_fight;
// mod build_building;
// mod upgrade_building;
// mod upgrade_compleate;
// mod start_mining;
// mod claim_mining;
// mod admin;
// mod attack_monster;
// mod open_pack;
// mod remove_build;